##Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head(20)

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
5,10556855,MINORITY ORGAN & TISSUE TRANSPLANT & EDUCATION...,T3,Independent,C1200,Preservation,Trust,1,0,N,5000,1
6,10558440,FRIENDS OF ARTS COUNCIL OF GREATER DENHAM SPRI...,T3,Independent,C1000,Preservation,Trust,1,100000-499999,N,31452,1
7,10566033,ISRAEL EMERGENCY ALLIANCE,T3,Independent,C2000,Preservation,Trust,1,10M-50M,N,7508025,1
8,10570430,ARAMCO BRATS INC,T7,Independent,C1000,ProductDev,Trust,1,1-9999,N,94389,1
9,10571689,INTERNATIONAL ASSOCIATION OF FIRE FIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
10,10573059,KAI ELUA OUTRIGGER CANOE CLUB,T3,Independent,C1200,Preservation,Trust,1,25000-99999,N,69656,0
11,10575727,HERITAGE ACADEMY,T3,Independent,C2000,Preservation,Trust,1,100000-499999,N,165593,0
12,10583569,THE UNITED STATES PONY CLUBS INC,T3,CompanySponsored,C1200,Preservation,Association,1,0,N,5000,1
13,10585206,DOMINION INTERNATIONAL NETWORK OF MINISTRIES &...,T3,Independent,C2700,Preservation,Trust,1,25000-99999,N,5301,1
14,10585443,V O W FOUNDATION,T3,Independent,C1000,Preservation,Trust,1,0,N,5000,1
15,10596727,JOSEPH E PEEBLES JR FOUNDATION,T3,Independent,C1200,Preservation,Trust,1,0,N,5000,1
16,10602428,WASHINGTON ASSOCIATION OF PHYSICIANS OF INDIAN...,T3,Independent,C2000,Preservation,Trust,1,0,N,5000,1
17,10603214,SAINT FRANCIS HOSPITAL SOUTH LLC,T3,Independent,C1000,Heathcare,Trust,1,50M+,N,86380556,0
18,10604986,ANCHORAGE COMMUNITY MENTAL HEALTH SERVICES,T3,CompanySponsored,C1000,Preservation,Trust,1,0,N,5000,0
19,10605038,HABITAT FOR HUMANITY INTERNATIONAL INC,T3,CompanySponsored,C1000,Preservation,Trust,1,100000-499999,N,376109,0

In [2]:
# Drop the non-beneficial ID columns, 'EIN','NAME' and others.
application_df = application_df.drop(columns= ["EIN", "NAME"])

In [3]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts for binning
app_counts = application_df["APPLICATION_TYPE"].value_counts()
app_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [5]:
# Look at ASK_AMT value counts for binning (the number of data points for each unique value)
ask_amount = application_df["ASK_AMT"].value_counts()
ask_amount

5000        25398
10478           3
15583           3
63981           3
6725            3
            ...
5371754         1
30060           1
43091152        1
18683           1
36500179        1
Name: ASK_AMT, Length: 8747, dtype: int64

In [6]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(app_counts[app_counts < 300].index)
application_types_to_replace

['T9', 'T13', 'T12', 'T2', 'T25', 'T14', 'T29', 'T15', 'T17']

In [7]:
# Replace in dataframe
for app in application_types_to_replace:
      application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [8]:
# Look at CLASSIFICATION value counts for binning
class_counts = application_df["CLASSIFICATION"].value_counts()
class_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [9]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(class_counts[class_counts < 1000].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [10]:
# Separate the features, X, from the target variable, y
X = application_df.drop(columns = "IS_SUCCESSFUL")
y = application_df["IS_SUCCESSFUL"]

In [11]:
# Preview the features data
X.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590

In [12]:
# Convert categorical data to numeric with `pd.get_dummies`
X = pd.get_dummies(X)
X.head()

,STATUS,ASK_AMT,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,APPLICATION_TYPE_T7,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,0,0,0,1,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,0,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,0,0,0,1,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [13]:
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 42)

In [14]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [15]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train.iloc[0])
hidden_layer1 = 20
hidden_layer2 = 15

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units = hidden_layer1, input_dim = number_input_features, activation = "relu"))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units = hidden_layer2, activation = "relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units = 1, activation = "sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 20)                880

 dense_1 (Dense)             (None, 15)                315

 dense_2 (Dense)             (None, 1)                 16

=================================================================
Total params: 1211 (4.73 KB)
Trainable params: 1211 (4.73 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [16]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [17]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=80)

Epoch 1/80
804/804 [==============================] - 7s 5ms/step - loss: 0.5915 - accuracy: 0.7103
Epoch 2/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5584 - accuracy: 0.7271
Epoch 3/80
804/804 [==============================] - 1s 2ms/step - loss: 0.5546 - accuracy: 0.7271
Epoch 4/80
804/804 [==============================] - 1s 2ms/step - loss: 0.5524 - accuracy: 0.7297
Epoch 5/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5511 - accuracy: 0.7299
Epoch 6/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5504 - accuracy: 0.7295
Epoch 7/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5496 - accuracy: 0.7298
Epoch 8/80
804/804 [==============================] - 1s 2ms/step - loss: 0.5487 - accuracy: 0.7308
Epoch 9/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5477 - accuracy: 0.7314
Epoch 10/80
804/804 [==============================] - 1s 2ms/step - loss: 0.5476 - accuracy: 0.7320
Epoch 11/80
804/804 [==============================] - 1s 2ms/step - loss: 0.5474 - accuracy: 0.7320
Epoch 12/80
804/804 [==============================] - 1s 2ms/step - loss: 0.5467 - accuracy: 0.7327
Epoch 13/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5463 - accuracy: 0.7332
Epoch 14/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5461 - accuracy: 0.7322
Epoch 15/80
804/804 [==============================] - 1s 2ms/step - loss: 0.5462 - accuracy: 0.7326
Epoch 16/80
804/804 [==============================] - 1s 2ms/step - loss: 0.5457 - accuracy: 0.7339
Epoch 17/80
804/804 [==============================] - 1s 2ms/step - loss: 0.5457 - accuracy: 0.7343
Epoch 18/80
804/804 [==============================] - 1s 2ms/step - loss: 0.5453 - accuracy: 0.7327
Epoch 19/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5448 - accuracy: 0.7342
Epoch 20/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5447 - accuracy: 0.7330
Epoch 21/80
804/804 [==============================] - 3s 3ms/step - loss: 0.5441 - accuracy: 0.7335
Epoch 22/80
804/804 [==============================] - 1s 2ms/step - loss: 0.5445 - accuracy: 0.7330
Epoch 23/80
804/804 [==============================] - 1s 2ms/step - loss: 0.5443 - accuracy: 0.7331
Epoch 24/80
804/804 [==============================] - 1s 2ms/step - loss: 0.5437 - accuracy: 0.7339
Epoch 25/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5435 - accuracy: 0.7345
Epoch 26/80
804/804 [==============================] - 1s 2ms/step - loss: 0.5439 - accuracy: 0.7338
Epoch 27/80
804/804 [==============================] - 1s 2ms/step - loss: 0.5435 - accuracy: 0.7350
Epoch 28/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5436 - accuracy: 0.7334
Epoch 29/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5435 - accuracy: 0.7348
Epoch 30/80
804/804 [==============================] - 1s 2ms/step - loss: 0.5429 - accuracy: 0.7341
Epoch 31/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5432 - accuracy: 0.7340
Epoch 32/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5430 - accuracy: 0.7349
Epoch 33/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5430 - accuracy: 0.7346
Epoch 34/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5430 - accuracy: 0.7348
Epoch 35/80
804/804 [==============================] - 5s 6ms/step - loss: 0.5425 - accuracy: 0.7352
Epoch 36/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5424 - accuracy: 0.7361
Epoch 37/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5422 - accuracy: 0.7345
Epoch 38/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5422 - accuracy: 0.7348
Epoch 39/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5427 - accuracy: 0.7338
Epoch 40/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5422 - accuracy: 0.7357
Epoch 41/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5415 - accuracy: 0.7355
Epoch 42/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5420 - accuracy: 0.7357
Epoch 43/80
804/804 [==============================] - 1s 2ms/step - loss: 0.5420 - accuracy: 0.7346
Epoch 44/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5420 - accuracy: 0.7351
Epoch 45/80
804/804 [==============================] - 1s 2ms/step - loss: 0.5418 - accuracy: 0.7349
Epoch 46/80
804/804 [==============================] - 1s 2ms/step - loss: 0.5420 - accuracy: 0.7355
Epoch 47/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5411 - accuracy: 0.7358
Epoch 48/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5415 - accuracy: 0.7358
Epoch 49/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5415 - accuracy: 0.7362
Epoch 50/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5412 - accuracy: 0.7353
Epoch 51/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5413 - accuracy: 0.7356
Epoch 52/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5409 - accuracy: 0.7360
Epoch 53/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5409 - accuracy: 0.7363
Epoch 54/80
804/804 [==============================] - 1s 2ms/step - loss: 0.5410 - accuracy: 0.7367
Epoch 55/80
804/804 [==============================] - 1s 2ms/step - loss: 0.5409 - accuracy: 0.7368
Epoch 56/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5408 - accuracy: 0.7356
Epoch 57/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5407 - accuracy: 0.7372
Epoch 58/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5409 - accuracy: 0.7353
Epoch 59/80
804/804 [==============================] - 1s 2ms/step - loss: 0.5403 - accuracy: 0.7363
Epoch 60/80
804/804 [==============================] - 1s 2ms/step - loss: 0.5407 - accuracy: 0.7351
Epoch 61/80
804/804 [==============================] - 1s 2ms/step - loss: 0.5402 - accuracy: 0.7367
Epoch 62/80
804/804 [==============================] - 1s 2ms/step - loss: 0.5405 - accuracy: 0.7345
Epoch 63/80
804/804 [==============================] - 1s 2ms/step - loss: 0.5405 - accuracy: 0.7367
Epoch 64/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5400 - accuracy: 0.7365
Epoch 65/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5401 - accuracy: 0.7372
Epoch 66/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5404 - accuracy: 0.7365
Epoch 67/80
804/804 [==============================] - 1s 2ms/step - loss: 0.5402 - accuracy: 0.7362
Epoch 68/80
804/804 [==============================] - 1s 2ms/step - loss: 0.5401 - accuracy: 0.7361
Epoch 69/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5399 - accuracy: 0.7355
Epoch 70/80
804/804 [==============================] - 1s 2ms/step - loss: 0.5403 - accuracy: 0.7362
Epoch 71/80
804/804 [==============================] - 1s 2ms/step - loss: 0.5400 - accuracy: 0.7358
Epoch 72/80
804/804 [==============================] - 2s 3ms/step - loss: 0.5401 - accuracy: 0.7357
Epoch 73/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5402 - accuracy: 0.7351
Epoch 74/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5401 - accuracy: 0.7364
Epoch 75/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5395 - accuracy: 0.7368
Epoch 76/80
804/804 [==============================] - 1s 2ms/step - loss: 0.5399 - accuracy: 0.7358
Epoch 77/80
804/804 [==============================] - 1s 2ms/step - loss: 0.5396 - accuracy: 0.7373
Epoch 78/80
804/804 [==============================] - 1s 2ms/step - loss: 0.5396 - accuracy: 0.7383
Epoch 79/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5397 - accuracy: 0.7367
Epoch 80/80
804/804 [==============================] - 2s 2ms/step - loss: 0.5395 - accuracy: 0.7360

In [18]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5540 - accuracy: 0.7255 - 494ms/epoch - 2ms/step
Loss: 0.5540066957473755, Accuracy: 0.7254810333251953